version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: python main.py
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
  

  # Test services
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: pytest -v --cov=. tests/

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm test
